version: "3.7"
services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  dbseed:
    build: ./mongo_seed
    links:
      - mongo

  api:
    build: .
    container_name: pokedex-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo