spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: pokedex
            collection: pokemons
    banner:
        location: banner.txt
logging:
    level:
        com: INFO
