spring:
    data:
        mongodb:
            host: mongo-container
#            username: root
#            password: senseicloud
#            authentication-database: admin

logging:
    level:
        com: DEBUG

